---
- hosts: all

  become: true
  tasks:   
    - name: Sending an e-mail
      community.general.mail:
        host: mail.prox-lab.de
        port: 587
        username: noreply@prox-lab.de
        password: a$n9FvSL2r4h&g
        to: info@prox-lab.de
        from: noreply@prox-lab.de (Ansible Semaphore)
        subject: Ansible-report
        body: Reboot required on {{ inventory_hostname }}
      # when: reboot_required.stat.exists
