---
- hosts: all

  become: true
  tasks:   
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: check if reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      
    - name: Sending an e-mail
      community.general.mail:
        host: "{{ mailhost }}"
        port: 587
        username: "{{ mailusername }}"
        password: "{{ mailpwd }}"
        to: "{{ mailtouser }}"
        from: "{{ mailfromuser }}"
        subject: Ansible-report
        body: Reboot required on {{ ansible_hostname }}
      when: reboot_required.stat.exists
